
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  namespace: esgis-devops
  name: mysql
spec:
  selector:
    app: webapp-sql
    tier: backend
  ports:
  - protocol: "TCP"
    port: 3306
    targetPort: 3306
  clusterIP: None

---
# MySQL Deploiment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqldb
  namespace: esgis-devops
  labels:
    app: webapp-sql
    tier: backend
spec:
  selector:
    matchLabels: 
      app: webapp-sql
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp-sql
        tier: backend
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        resources:
          limits:
            memory: "1024Mi"
            cpu: "512m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        - name: MYSQL_DATABASE
          value: devopsdb
        - name: MYSQL_USER
          value: esgis
        - name: MYSQL_PASSWORD
          value: esgis
        args: 
          - --default-authentication-plugin=mysql_native_password
          - --character-set-server=utf8mb4 
          - --collation-server=utf8mb4_unicode_520_ci
        ports:
        - containerPort: 3306