
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: webapp-sql
    tier: backend
  ports:
  - protocol: "TCP"
    port: 3306
    targetPort: 3306
  clusterIP: None

---
# MySQL Deploiment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqldb
  namespace: esgis-devops
  labels:
    app: webapp-sql
    tier: backend
spec:
  selector:
    matchLabels: 
      app: webapp-sql
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp-sql
        tier: backend
    spec:
      containers:
      - image: mysql
        name: mysql
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-user
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: web-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: web-pwd
        args: 
          - --default-authentication-plugin=mysql_native_password
          - --character-set-server=utf8mb4 
          - --collation-server=utf8mb4_unicode_520_ci
        ports:
        - containerPort: 3306